Rails.application.routes.default_url_options = { host: "http://#{ENV['store_host']}", port: ENV['store_port'] }
Rails.application.routes.draw do
  namespace :admin do
    controller :pages do
      get :dashboard
    end

    resources :products, except:  [:destroy] do
      member do
        delete :display_picture,  action: :remove_display_picture
        delete :images,           action: :remove_image
      end
    end
    resources :purchases, only:   [:index, :show]

    root to: 'pages#dashboard'
  end

  namespace :api do
    namespace :v1 do
      namespace :store do
        resources :paypal_purchases, only: [:create]
      end
    end
  end

  namespace :store do
    resources :links, only: :show
    resources :products,  only: [:index, :show]
    resources :purchases, only: [:show] do
      collection do
        get :failure
      end
      member do
        get :success
      end
    end
  end

  # STATIC PAGES
  get '/about', to: 'store/pages#about'

  root to: 'store/products#index'

  # Exceptions routing
  get '/404', to: 'errors#not_found'
  get '/422', to: 'errors#unacceptable'
  get '/500', to: 'errors#internal_error'

  # generated by Clearance gem
  resources :passwords, controller: "clearance/passwords",  only: [:create, :new]
  resource  :session,   controller: "clearance/sessions",   only: [:create]
  resources :users,     controller: "clearance/users",      only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:edit, :update]
  end
  get     "/sign_in",   to: "clearance/sessions#new",       as: "sign_in"
  delete  "/sign_out",  to: "clearance/sessions#destroy",  as: "sign_out"
  get     "/sign_up",   to: "clearance/users#new",          as: "sign_up"  
end
