env:
  RUBY_VERSION: 2.6
  NODE_VERSION: 12

name: spec
on: [push, pull_request]
jobs:
  rspec-test:
    name: RSpec
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
          check-latest: true
      - run: npm install --global yarn
      - run: npm install
      - run: npm test
      - run: yarn
      - name: Install database client
        run: |
          sudo apt-get install sqlite3
          sqlite3 --version
      - name: Install gem dependencies
        run: |
          gem install bundler
          gem install execjs -v '2.7.0'
          bundler install
      - name: Create database
        run: |
          bundler exec rails db:create RAILS_ENV=test
          bundler exec rails db:migrate RAILS_ENV=test
      - name: Run tests
        run: bundler exec rspec  
      - name: Upload coverage results    
        uses: actions/upload-artifact@master
        if: always()
        with:
          name: coverage-report
          path: coverage              